# Generated by Django 5.1.7 on 2025-04-07 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="blog_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.blogcategory",
            ),
        ),
        migrations.AddField(
            model_name="blogcategorymapping",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
            ),
        ),
        migrations.AddField(
            model_name="blogcategorymapping",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogcategory"
            ),
        ),
        migrations.AddField(
            model_name="blogsection",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="blog.blog",
            ),
        ),
        migrations.AddField(
            model_name="blogtagmapping",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
            ),
        ),
        migrations.AddField(
            model_name="blogtagmapping",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogtag"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="blog_tags",
            field=models.ManyToManyField(
                through="blog.BlogTagMapping", to="blog.blogtag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blogcategorymapping",
            unique_together={("blog", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="blogtagmapping",
            unique_together={("blog", "tag")},
        ),
    ]
