# Generated by Django 5.1.7 on 2025-04-07 06:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="blogs/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="blog_snippet",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Excerpt"
            ),
        ),
    ]
