# Generated by Django 5.1.7 on 2025-04-07 08:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_blog_featured_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Content"
            ),
        ),
        migrations.DeleteModel(
            name="BlogSection",
        ),
    ]
