# Generated by Django 5.1.7 on 2025-04-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_blog_author_blog_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="Draft",
                max_length=10,
            ),
        ),
    ]
