# Generated by Django 5.1.7 on 2025-04-08 17:06

import django.utils.timezone
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_title", models.CharField(max_length=200, unique=True)),
                (
                    "course_slug",
                    models.SlugField(blank=True, max_length=200, unique=True),
                ),
                (
                    "course_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_images/"
                    ),
                ),
                (
                    "course_image_alt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "course_price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "course_short_description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Short Description"
                    ),
                ),
                (
                    "course_long_description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Long Description"
                    ),
                ),
                (
                    "course_learning_outcomes",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Learning Outcomes"
                    ),
                ),
                (
                    "course_pre_requisites",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Pre Requisites"
                    ),
                ),
                (
                    "course_target_audience",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Who Is The Course For"
                    ),
                ),
                ("course_language", models.CharField(default="English", max_length=50)),
                ("course_preview_video", models.URLField(blank=True, null=True)),
                ("course_card_json", models.JSONField(blank=True, null=True)),
                ("course_overview_json", models.JSONField(blank=True, null=True)),
                ("course_content_json", models.JSONField(blank=True, null=True)),
                ("course_created_at", models.DateTimeField(auto_now_add=True)),
                ("course_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "course_published_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "course_category_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_category_name", models.CharField(max_length=100, unique=True)),
                ("course_category_slug", models.SlugField(blank=True, unique=True)),
                ("course_category_created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseCategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseChapter",
            fields=[
                (
                    "course_chapter_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_chapter_title", models.CharField(max_length=200)),
                (
                    "course_chapter_order",
                    models.PositiveIntegerField(
                        help_text="Order of the chapter in the course"
                    ),
                ),
                ("course_chapter_created_at", models.DateTimeField(auto_now_add=True)),
                ("course_chapter_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["course_chapter_order"],
            },
        ),
        migrations.CreateModel(
            name="CourseEnrolled",
            fields=[
                (
                    "course_enrollment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_enrolled_created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseQuiz",
            fields=[
                (
                    "course_quiz_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_quiz_title", models.CharField(max_length=200)),
                ("course_quiz_json", models.JSONField(blank=True, null=True)),
                ("course_quiz_created_at", models.DateTimeField(auto_now_add=True)),
                ("course_quiz_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseTopic",
            fields=[
                (
                    "course_topic_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_topic_title", models.CharField(max_length=200)),
                (
                    "course_topic_content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Content"
                    ),
                ),
                (
                    "course_topic_order",
                    models.PositiveIntegerField(
                        help_text="Order of the topics in the chapter"
                    ),
                ),
                (
                    "course_topic_video_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional video link for the course topic",
                        null=True,
                    ),
                ),
                ("course_topic_created_at", models.DateTimeField(auto_now_add=True)),
                ("course_topic_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["course_topic_order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswerMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "question_option_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_option", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "quiz_question_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quiz_question", models.CharField(max_length=250)),
            ],
        ),
    ]
