# Generated by Django 5.1.7 on 2025-04-08 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coursecategorymapping",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="coursecategorymapping",
            name="course_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.coursecategory"
            ),
        ),
        migrations.AddField(
            model_name="coursechapter",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="courseenrolled",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="courseenrolled",
            name="course_enrolled_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="coursequiz",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="courses.coursechapter",
            ),
        ),
        migrations.AddField(
            model_name="coursetopic",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="courses.coursechapter",
            ),
        ),
        migrations.AddField(
            model_name="questionanswermapping",
            name="quiz_question_answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.questionoption"
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.coursechapter",
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="courses.coursequiz",
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.coursetopic",
            ),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="courses.quizquestion",
            ),
        ),
        migrations.AddField(
            model_name="questionanswermapping",
            name="quiz_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.quizquestion"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursecategorymapping",
            unique_together={("course", "course_category")},
        ),
        migrations.AlterUniqueTogether(
            name="courseenrolled",
            unique_together={("course", "course_enrolled_user")},
        ),
    ]
