# Generated by Django 5.1.7 on 2025-04-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_structure",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="Draft",
                max_length=10,
            ),
        ),
    ]
